# build
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /src
ADD . /src
ARG PROJECT_KEY
ARG SONAR_HOST
ARG SONAR_LOGIN
RUN mvn -e -s .m2/settings.xml clean deploy sonar:sonar \
                -Dsonar.projectKey=${PROJECT_KEY} \
                -Dsonar.host.url=${SONAR_HOST} \
                -Dsonar.login=${SONAR_LOGIN}
